### ISSUE TITLE
How install ckeditor plugin?

### ISSUE THREAD

**Issue by zhuravskiy** [OpenESignForms/vaadin-ckeditor#44]
```
Copy the plugin files to the plugins folder of your CKEditor installation. Each plugin must be placed in a sub-folder that matches its "technical" name.

For example, the Language plugin would be installed into this folder: <CKEditor folder>/plugins/language.
```
from http://docs.ckeditor.com/#!/guide/dev_plugins

**Comment by OpenESignForms** [comment]
Didn't notice this issue before...  I don't know how to make end user CKEditor plugins work automatically with our Vaadin adapter.  That is, the CKEditor plugins today must be in the standard ckeditor location so it can load via the Vaadin widgetset.  We are open to patches that can accommodate what you are asking for, though it's possible a pure Vaadin 7 javascript interface (rather than our legacy connector originally built on Vaadin 6) would be a better project for someone to create.

**Comment by OpenESignForms** [comment]
Closing for lack of info and direction.
