### ISSUE TITLE
CKEditor does not update value when used with a FieldGroup

### ISSUE THREAD

**Issue by EduFrazao** [OpenESignForms/vaadin-ckeditor#53]
After update to CKEditor Wrapper 7.10.7, when a new ItemDataSource is placed on a FieldGroup, CKEditor does not show the value. All other fields bound on the FieldGroup works.

**Comment by OpenESignForms** [comment]
Rats.  I'm guessing this is related to the patch provided for this release that was designed to resolve an issue 52 with long polling.  

https://github.com/OpenESignForms/vaadin-ckeditor/pull/52

It appears that when you set the item data source, the new value is not making the rounds.  For now, just use 7.10.6 as the only other update was a new version of CKEditor itself that didn't seem like an important update for most uses.  

Please let us know if 7.10.6 resolves it for you as we'll be sure that the bug is in that patch from Matti, and perhaps he will have some idea what is missing to enable his code to work.

**Comment by EduFrazao** [comment]
You are right. 7.10.6 is working fine. Should I close this bug?

**Comment by OpenESignForms** [comment]
No, please keep it open as the bug still needs to be resolved.  Thanks for noting the patch fix created this bug and by removing it all is good.  We'll see if the author of that patch has a way to make it work on setting a new item data source as that seems more fundamental than handling cursor repositioning for those using long polling.

**Comment by EduFrazao** [comment]
Thank you by your fast answer. Right now i'm very busy, but if the patch owner does not publish a solution, I will try to check this out on this weekend.

**Comment by mstahv** [comment]
I think this should do it:
https://github.com/mstahv/vaadin-ckeditor/commit/6823888f16729ea1abd7182c08941ac4cf514aef

**Comment by OpenESignForms** [comment]
Thanks, Matti.  We'll put this together along with the latest CKEditor update and get it out shortly.
